PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX stax: <https://w3id.org/stax/ontology#>

SELECT * WHERE {
    ?baseStreamType a stax:ConcreteRdfStreamType ;
        # No need for using a "skos:broader*/" path here, as the reasoner will infer 
        # the needed stax:canBeTriviallyExtendedInto statements automatically.
  		stax:canBeTriviallyExtendedInto ?extendedStreamType .
}
