site_name: RDF-STaX
site_description: RDF Stream Taxonomy (RDF-STaX)
site_url: https://rdf-stax.github.io/
edit_uri: edit/main/docs/

plugins:
  - search
  - include-markdown
  - mike
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_url: https://github.com/RDF-STaX/rdf-stax.github.io
repo_name: RDF-STaX/rdf-stax.github.io

theme:
  name: material
  custom_dir: overrides
  features:
    # Behave like an SPA
    - navigation.instant
    - navigation.instant.progress
    # Update anchors in the address bar
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

  font:
    text: Lato

  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

  logo: assets/logo_white.png
  favicon: assets/logo_color.png
  icon:
    repo: fontawesome/brands/github

extra:
  version:
    provider: mike
    default: 
      - latest
      - stable
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RDF-STaX
      name: RDF-STaX on GitHub

nav:
  - Home: 'index.md'
  - Taxonomy overview: taxonomy.md
  - Ontology documentation: 'ontology.md'
  - How to use it?: 'use-it.md'
  - Nanopublications: 'nanopubs.md'
  - Use cases and publications:
    - 'uses/index.md'
    - Competency question tests: 'uses/cq.md'
  - Contributing: 'contributing.md'
  - Licensing and citation: 'licensing.md'
