site_name: RDF-STaX
site_description: RDF Stream Taxonomy (RDF-STaX)
site_url: https://rdf-stax.github.io/
edit_uri: edit/main/docs/

plugins:
  - search
  - include-markdown
  - mike

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.twemoji

repo_url: https://github.com/RDF-STaX/rdf-stax.github.io
repo_name: RDF-STaX/rdf-stax.github.io

theme:
  name: material
  # TODO: custom scripts
  custom_dir: overrides
  features:
    # Behave like an SPA
    - navigation.instant
    - navigation.instant.progress
    # Update anchors in the address bar
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

  font:
    text: Lato

  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

  logo: assets/logo_white.png
  favicon: assets/logo_color.png
  icon:
    repo: fontawesome/brands/github

extra:
  version:
    provider: mike
    default: stable
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RDF-STaX
      name: RDF-STaX on GitHub

nav:
  - Home: 'index.md'
  - How to use it?: 'overview.md'
  - Ontology docs: 'ontology.md'
  - Nanopublications: 'nanopubs.md'
  - RDF-STaX uses and publications: 'uses.md'
  - Contributing: 'contributing.md'
  - Licensing and citation: 'licensing.md'
