PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX stax: <https://w3id.org/stax/ontology#>

SELECT * WHERE {
    {
        ?streamType skos:broader+ ?streamType .
    }
    UNION
    {
        ?streamType skos:narrower+ ?streamType .
    }
}
